/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingui;

import connection.dbconnection;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hansaka Peiris
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }
    public void ClearCustomer(){
           custNamet.setText("");
           custAddt.setText("");
           custEmailt.setText("");
           custTPL.setText("");
    
    
    }
    public void savecustomer(){
        try {
            
            String s1=custNamet.getText();
            String s2=custAddt.getText();
            String s3=custEmailt.getText();
            String s4=custTPL.getText();
            
            
            Connection c= dbconnection.dbconmethod();
            Statement s= c.createStatement();
            
            s.executeQuery("INSERT INTO customer (customer_name,customer_address,customer_email,customer_telephone) VALUES('"+s1+"','"+s2+"','"+s3+"','"+s4+"')");
            JOptionPane.showMessageDialog(new swingui.Home(),"Saved Succesfully","Saved Alert",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        custNamel = new javax.swing.JLabel();
        custNamet = new javax.swing.JTextField();
        custAddressl = new javax.swing.JLabel();
        custAddt = new javax.swing.JTextField();
        custEmaill = new javax.swing.JLabel();
        custEmailt = new javax.swing.JTextField();
        custTPL = new javax.swing.JLabel();
        custTPl = new javax.swing.JTextField();
        custIDL = new javax.swing.JLabel();
        custIDAGL = new javax.swing.JLabel();
        btn_cusclear = new javax.swing.JButton();
        btn_cusok = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_cusupdate = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        supname = new javax.swing.JTextField();
        btn_supsearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        custClear1 = new javax.swing.JButton();
        custAddressl1 = new javax.swing.JLabel();
        cuscombo = new javax.swing.JComboBox<>();
        cussearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custNamel.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custNamel.setText("Name");
        jPanel2.add(custNamel, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 195, 135, 42));

        custNamet.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        custNamet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNametActionPerformed(evt);
            }
        });
        jPanel2.add(custNamet, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 195, 421, 42));

        custAddressl.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custAddressl.setText("Address");
        jPanel2.add(custAddressl, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 244, 135, 42));

        custAddt.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        custAddt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddtActionPerformed(evt);
            }
        });
        jPanel2.add(custAddt, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 244, 421, 42));

        custEmaill.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custEmaill.setText("Email");
        jPanel2.add(custEmaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 293, 135, 42));

        custEmailt.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        custEmailt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custEmailtActionPerformed(evt);
            }
        });
        jPanel2.add(custEmailt, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 293, 421, 42));

        custTPL.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custTPL.setText("Telephone No:");
        jPanel2.add(custTPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 342, 135, 42));

        custTPl.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        custTPl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custTPlActionPerformed(evt);
            }
        });
        jPanel2.add(custTPl, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 342, 421, 42));

        custIDL.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custIDL.setText("Customer ID");
        jPanel2.add(custIDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 391, 135, 42));

        custIDAGL.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custIDAGL.setText("Customer ID");
        jPanel2.add(custIDAGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 391, 135, 42));

        btn_cusclear.setBackground(new java.awt.Color(51, 102, 255));
        btn_cusclear.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_cusclear.setForeground(new java.awt.Color(255, 255, 255));
        btn_cusclear.setText("Clear");
        btn_cusclear.setBorder(null);
        btn_cusclear.setBorderPainted(false);
        btn_cusclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cusclearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cusclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 542, 124, 33));

        btn_cusok.setBackground(new java.awt.Color(51, 102, 255));
        btn_cusok.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_cusok.setForeground(new java.awt.Color(255, 255, 255));
        btn_cusok.setText("OK");
        btn_cusok.setBorder(null);
        btn_cusok.setBorderPainted(false);
        btn_cusok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cusokActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cusok, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 542, 124, 32));

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        jLabel14.setText("Customer Data");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 32, 374, 74));

        btn_cusupdate.setBackground(new java.awt.Color(51, 102, 255));
        btn_cusupdate.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_cusupdate.setForeground(new java.awt.Color(255, 255, 255));
        btn_cusupdate.setText("Update");
        btn_cusupdate.setBorder(null);
        btn_cusupdate.setBorderPainted(false);
        btn_cusupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cusupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cusupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 542, 124, 33));

        Delete.setBackground(new java.awt.Color(51, 102, 255));
        Delete.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Clear");
        Delete.setBorder(null);
        Delete.setBorderPainted(false);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 542, 124, 33));

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        supname.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        supname.setText("Enter Customer ID");
        supname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supnameActionPerformed(evt);
            }
        });

        btn_supsearch.setBackground(new java.awt.Color(255, 51, 0));
        btn_supsearch.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        btn_supsearch.setForeground(new java.awt.Color(255, 255, 255));
        btn_supsearch.setText("Search");
        btn_supsearch.setBorder(null);
        btn_supsearch.setBorderPainted(false);
        btn_supsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supname, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btn_supsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(supname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_supsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 480, 210));

        jTabbedPane1.addTab("Add ", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Roboto Condensed", 1, 48)); // NOI18N
        jLabel15.setText("Customer Data");

        jTable1.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Address", "E-Mail", "Telephone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        custClear1.setBackground(new java.awt.Color(51, 102, 255));
        custClear1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        custClear1.setForeground(new java.awt.Color(255, 255, 255));
        custClear1.setText("Update");
        custClear1.setBorder(null);
        custClear1.setBorderPainted(false);
        custClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custClear1ActionPerformed(evt);
            }
        });

        custAddressl1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        custAddressl1.setText("Search Via");

        cuscombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cuscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer ID", "Customer Name" }));
        cuscombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuscomboActionPerformed(evt);
            }
        });

        cussearch.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        cussearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cussearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(custAddressl1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cuscombo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cussearch, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuscombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custAddressl1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cussearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(custClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1635, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1072, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("View ", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1640, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custNametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNametActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNametActionPerformed

    private void custAddtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAddtActionPerformed

    private void custEmailtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custEmailtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custEmailtActionPerformed

    private void custTPlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custTPlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custTPlActionPerformed

    private void btn_cusclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cusclearActionPerformed
        ClearCustomer();
    }//GEN-LAST:event_btn_cusclearActionPerformed

    private void btn_cusokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cusokActionPerformed
        savecustomer();
        ClearCustomer();
    }//GEN-LAST:event_btn_cusokActionPerformed

    private void custClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custClear1ActionPerformed

    private void btn_cusupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cusupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cusupdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void supnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supnameActionPerformed

    private void btn_supsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supsearchActionPerformed

    private void cuscomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuscomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuscomboActionPerformed

    private void cussearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cussearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cussearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton btn_cusclear;
    private javax.swing.JButton btn_cusok;
    private javax.swing.JButton btn_cusupdate;
    private javax.swing.JButton btn_supsearch;
    private javax.swing.JComboBox<String> cuscombo;
    private javax.swing.JTextField cussearch;
    private javax.swing.JLabel custAddressl;
    private javax.swing.JLabel custAddressl1;
    private javax.swing.JTextField custAddt;
    private javax.swing.JButton custClear1;
    private javax.swing.JLabel custEmaill;
    private javax.swing.JTextField custEmailt;
    private javax.swing.JLabel custIDAGL;
    private javax.swing.JLabel custIDL;
    private javax.swing.JLabel custNamel;
    private javax.swing.JTextField custNamet;
    private javax.swing.JLabel custTPL;
    private javax.swing.JTextField custTPl;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField supname;
    // End of variables declaration//GEN-END:variables
}
